# Generated by Django 4.2 on 2023-04-20 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asn', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('ignored_status', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('protocol', models.CharField(max_length=50, null=True)),
                ('owner', models.CharField(max_length=50, null=True)),
                ('service', models.CharField(max_length=50, null=True)),
                ('rpc_info', models.CharField(max_length=50, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('host_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.host')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('O', 'OPEN'), ('C', 'CLOSE')], default='O', max_length=50)),
                ('network', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('compony_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campany')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='scan_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.network'),
        ),
    ]
