# Generated by Django 4.1.7 on 2023-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_errorlog_userlog_delete_userloggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campany',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campany',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='port',
            name='service',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scancase',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
