# Generated by Django 4.1.7 on 2023-05-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_campany_owner_alter_campany_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='scan_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='main.scancase'),
        ),
    ]
