# Generated by Django 4.2.1 on 2023-05-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_host_scan_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='service',
            field=models.JSONField(null=True),
        ),
    ]
