# Generated by Django 4.2.1 on 2023-05-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_port_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='service',
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150, null=True)),
                ('value', models.CharField(max_length=500, null=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.host')),
            ],
        ),
    ]
