# Generated by Django 4.2.1 on 2023-05-30 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_port_service_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.port'),
        ),
    ]
