# Generated by Django 4.2.1 on 2023-06-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_service_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='port',
            name='rpc_info',
        ),
        migrations.RemoveField(
            model_name='port',
            name='version',
        ),
    ]
