# Generated by Django 4.2.2 on 2023-06-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userloggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='devive',
            field=models.TextField(null=True),
        ),
    ]
