# Generated by Django 4.2.2 on 2023-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_errorlog_devive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
