# Generated by Django 4.2.2 on 2023-06-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_errorlog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='devive',
            new_name='device',
        ),
    ]
