# Generated by Django 4.2.2 on 2023-06-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_userloggers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
