# Generated by Django 4.2.2 on 2023-06-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_errorlog_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campany',
            name='asn',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='scancase',
            name='scan_date',
            field=models.DateField(default=False, unique=True),
        ),
    ]
